### ISSUE TITLE
Something missing?!

### ISSUE THREAD

**Issue by biscuitbarrel** [rayryeng/XiaohuLuVPDetection#3]
Not sure if this project has been canned/sabotaged or what?!

Trying to install and  when running "python setup.py build" I get...

       file lu_vp_detect.py (for module lu_vp_detect) not found

I had to manually create the __version__.py file to get this far.

Please let me know one way or the other if this can be resurrected
Thanks
Stef

Forget this, I resolved my installation problem

**Comment by biscuitbarrel** [comment]
There seems to be a problem in OpenCV.
When I use the test image I get...

Traceback (most recent call last):
  File "C:\Users\stef\AppData\Local\Programs\Python\Python36\Scripts\run_vp_detect-script.py", line 11, in <module>
    load_entry_point('lu-vp-detect==1.0.0', 'console_scripts', 'run_vp_detect')()
  File "C:\Users\stef\AppData\Local\Programs\Python\Python36\lib\site-packages\lu_vp_detect-1.0.0-py3.6.egg\lu_vp_detect\run_vp_detect.py", line 68, in main
  File "C:\Users\stef\AppData\Local\Programs\Python\Python36\lib\site-packages\lu_vp_detect-1.0.0-py3.6.egg\lu_vp_detect\vp_detection.py", line 523, in find_vps
  File "C:\Users\stef\AppData\Local\Programs\Python\Python36\lib\site-packages\lu_vp_detect-1.0.0-py3.6.egg\lu_vp_detect\vp_detection.py", line 164, in __detect_lines
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\lsd.cpp:143: error: (-213:The function/feature is not implemented) Implementation has been removed due original code license issues in function 'cv::LineSegmentDetectorImpl::LineSegmentDetectorImpl'

**Comment by rayryeng** [comment]
@biscuitbarrel This is because the LSD detector has been removed in OpenCV 4.1.0 due to licensing issues.  I will update the repo so that OpenCV 3.x should be used.  Thanks for letting me know.

**Comment by biscuitbarrel** [comment]
Thanks for the fix.
My little application works very well!
